### PR TITLE
MNT: Add stdlib c build dependency

### PR DESCRIPTION
**Pull request by matthewfeickert**
* Add required '{{ stdlib("c") }}' build dependency as a compiler is used in the build recipe.
   - c.f. https://conda-forge.org/news/2024/03/24/stdlib-migration/
* Bump build number.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please re-render

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please re-render

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please re-render

**Comment by matthewfeickert** [comment]
@conda-forge/lhapdf this is ready for review. Let me know if you have any questions.

**Comment by scarlehoff** [comment]
Hi @matthewfeickert , thank you very much!

**Comment by matthewfeickert** [comment]
@scarlehoff Thank you very much for putting LHAPDF on conda-forge! I was going to have a student work on this and then found you had done the work for us. 😃

**Pull request merged**
