### PR TITLE
V6.5.4

### PR DESCRIPTION
**Pull request by Zaharid**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Zaharid** [comment]
Importing the python module is segfaulting on mac. 

@scarlehoff could you have a look?

**Comment by scarlehoff** [comment]
The version of `lhapdf` in homebrew is still at 6.5.3 https://github.com/davidchall/homebrew-hep/blob/HEAD/Formula/lhapdf.rb

so I'd simply wait. Is there some bugfix in 6.5.4 that we need?

**Comment by Zaharid** [comment]
AFAICT the internal uncertainty calculation is wrong, which is used in various places, but not nnpdf.

**Comment by scarlehoff** [comment]
I just tested it and it does work in M1. And since it works I've opened a PR so that the arm64 build is enabled https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4584 (it's silly not to have it if it works).

Not sure when/where I will be able to get my hands on an "old mac". Maybe @Radonirinaunimi could help here (I was with him last week but forgot about this).

**Comment by Radonirinaunimi** [comment]
> I just tested it and it does work in M1. And since it works I've opened a PR so that the arm64 build is enabled [conda-forge/conda-forge-pinning-feedstock#4584](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4584) (it's silly not to have it if it works).
> 
> Not sure when/where I will be able to get my hands on an "old mac". Maybe @Radonirinaunimi could help here (I was with him last week but forgot about this).

Yes, I can try to have a look asap!

**Pull request closed without merging**
